//! Checks the Rust rules against `fixtures/core.json`, generated by the web app's
//! `src/domain/conformance.test.ts`. Any difference means the server and the app would
//! disagree about what the user sees.

use std::collections::BTreeMap;

use chrono::{DateTime, NaiveDate, NaiveDateTime, Utc};
use habit_core::dates::{
    DateRange, DurationUnit, end_of_duration, minutes_into_day, period_range, to_local_date,
};
use habit_core::notify::progress_ready_to_alert;
use habit_core::schedule::{describe_schedule, next_run};
use habit_core::status::{
    Overview, PeriodStatus, TaskContext, TaskSummary, exceptions_for_task, overview,
    period_history, period_status, summarize,
};
use habit_core::types::{Period, Schedule, TaskEvent, TaskException};
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fixture {
    today: NaiveDate,
    status: Vec<StatusCase>,
    overview: OverviewCase,
    exceptions_for_task: ExceptionsCase,
    period_range: Vec<PeriodRangeCase>,
    to_local_date: Vec<ToLocalDateCase>,
    minutes_into_day: Vec<MinutesCase>,
    end_of_duration: Vec<DurationCase>,
    schedules: Vec<ScheduleCase>,
    progress_ready_to_alert: Vec<AlertCase>,
}

#[derive(Deserialize)]
struct StatusCase {
    name: String,
    ctx: TaskContext,
    statuses: BTreeMap<NaiveDate, PeriodStatus>,
    summary: TaskSummary,
    history: Vec<PeriodStatus>,
}

#[derive(Deserialize)]
struct OverviewCase {
    cases: Vec<String>,
    result: Overview,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ExceptionsCase {
    exceptions: Vec<TaskException>,
    task_id: String,
    category_ids: Vec<String>,
    result: Vec<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct PeriodRangeCase {
    period: Period,
    date: NaiveDate,
    week_starts_on: u8,
    result: DateRange,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ToLocalDateCase {
    moment: String,
    day_start_hour: u32,
    result: NaiveDate,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct MinutesCase {
    time: String,
    day_start_hour: u32,
    result: u32,
}

#[derive(Deserialize)]
struct DurationCase {
    start: NaiveDate,
    count: f64,
    unit: DurationUnit,
    result: NaiveDate,
}

#[derive(Deserialize)]
struct ScheduleCase {
    schedule: Schedule,
    from: String,
    describe: String,
    next: Option<String>,
}

#[derive(Deserialize)]
struct AlertCase {
    events: Vec<TaskEvent>,
    since: DateTime<Utc>,
    now: DateTime<Utc>,
    result: Vec<String>,
}

fn load() -> Fixture {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/core.json");
    let text =
        std::fs::read_to_string(path).expect("fixtures/core.json exists (run the web app's tests)");
    serde_json::from_str(&text).expect("fixture parses")
}

fn naive(s: &str) -> NaiveDateTime {
    NaiveDateTime::parse_from_str(s, "%Y-%m-%dT%H:%M").expect("naive datetime")
}

#[test]
fn period_status_summary_and_history() {
    let f = load();
    let mut failures = Vec::new();
    for case in &f.status {
        for (date, expected) in &case.statuses {
            let actual = period_status(&case.ctx, *date, f.today);
            if &actual != expected {
                failures.push(format!(
                    "{} @ {date}:\n  expected {expected:?}\n  actual   {actual:?}",
                    case.name
                ));
            }
        }
        let summary = summarize(&case.ctx, f.today);
        if summary != case.summary {
            failures.push(format!(
                "{} summary:\n  expected {:?}\n  actual   {summary:?}",
                case.name, case.summary
            ));
        }
        let history = period_history(&case.ctx, f.today, 10);
        if history != case.history {
            let at = history.iter().zip(&case.history).position(|(a, b)| a != b);
            failures.push(match at {
                Some(i) => format!(
                    "{} history differs at period {i} ({})",
                    case.name, case.history[i].range.start
                ),
                None => format!(
                    "{} history: expected {} periods, got {}",
                    case.name,
                    case.history.len(),
                    history.len()
                ),
            });
        }
    }
    assert!(
        failures.is_empty(),
        "{} mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn overview_across_cases() {
    let f = load();
    assert_eq!(f.overview.cases.len(), f.status.len());
    let currents: Vec<PeriodStatus> = f
        .status
        .iter()
        .map(|c| period_status(&c.ctx, f.today, f.today))
        .collect();
    let actual = overview(
        f.status
            .iter()
            .zip(&currents)
            .map(|(c, s)| (&c.ctx.task, s)),
    );
    assert_eq!(actual, f.overview.result);
}

#[test]
fn exceptions_by_scope() {
    let f = load();
    let c = &f.exceptions_for_task;
    let ids: Vec<&str> = exceptions_for_task(&c.task_id, &c.category_ids, &c.exceptions)
        .into_iter()
        .map(|e| e.id.as_str())
        .collect();
    assert_eq!(ids, c.result);
}

#[test]
fn dates() {
    let f = load();
    for c in &f.period_range {
        assert_eq!(
            period_range(c.period, c.date, c.week_starts_on),
            c.result,
            "{:?} {} ws={}",
            c.period,
            c.date,
            c.week_starts_on
        );
    }
    for c in &f.to_local_date {
        assert_eq!(
            to_local_date(naive(&c.moment), c.day_start_hour),
            c.result,
            "{} dsh={}",
            c.moment,
            c.day_start_hour
        );
    }
    for c in &f.minutes_into_day {
        assert_eq!(
            minutes_into_day(&c.time, c.day_start_hour),
            c.result,
            "{} dsh={}",
            c.time,
            c.day_start_hour
        );
    }
    for c in &f.end_of_duration {
        assert_eq!(
            end_of_duration(c.start, c.count, c.unit),
            c.result,
            "{} {} {:?}",
            c.start,
            c.count,
            c.unit
        );
    }
}

#[test]
fn schedules() {
    let f = load();
    for c in &f.schedules {
        assert_eq!(describe_schedule(&c.schedule), c.describe);
        let next =
            next_run(&c.schedule, naive(&c.from)).map(|d| d.format("%Y-%m-%dT%H:%M").to_string());
        assert_eq!(next, c.next, "{:?} from {}", c.schedule, c.from);
    }
}

#[test]
fn progress_alert_delay() {
    let f = load();
    for c in &f.progress_ready_to_alert {
        let ids: Vec<&str> = progress_ready_to_alert(&c.events, c.since, c.now)
            .into_iter()
            .map(|e| e.id.as_str())
            .collect();
        assert_eq!(ids, c.result, "since {} now {}", c.since, c.now);
    }
}
