import {
  Apple,
  Bed,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Candy,
  Church,
  Circle,
  Coffee,
  Droplets,
  Dumbbell,
  Footprints,
  Gamepad2,
  Guitar,
  Heart,
  IceCreamCone,
  Laptop,
  Leaf,
  type LucideIcon,
  MonitorPlay,
  Moon,
  Music,
  Pencil,
  Phone,
  Pill,
  Salad,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Sun,
  Utensils,
  Users,
  Wine,
} from "lucide-react"

// A curated set keeps the picker usable and the bundle small.
export const TASK_ICONS: Record<string, LucideIcon> = {
  circle: Circle,
  dumbbell: Dumbbell,
  footprints: Footprints,
  bike: Bike,
  heart: Heart,
  "book-open": BookOpen,
  church: Church,
  brain: Brain,
  pencil: Pencil,
  sun: Sun,
  moon: Moon,
  bed: Bed,
  droplets: Droplets,
  pill: Pill,
  apple: Apple,
  salad: Salad,
  utensils: Utensils,
  coffee: Coffee,
  "ice-cream-cone": IceCreamCone,
  candy: Candy,
  wine: Wine,
  "monitor-play": MonitorPlay,
  smartphone: Smartphone,
  "gamepad-2": Gamepad2,
  laptop: Laptop,
  briefcase: Briefcase,
  "shopping-cart": ShoppingCart,
  music: Music,
  guitar: Guitar,
  users: Users,
  phone: Phone,
  leaf: Leaf,
  sparkles: Sparkles,
}

export const COLORS = [
  "#ef4444",
  "#f97316",
  "#eab308",
  "#22c55e",
  "#14b8a6",
  "#3b82f6",
  "#6366f1",
  "#a855f7",
  "#ec4899",
  "#64748b",
]
